// Mocks generated by Mockito 5.4.6 from annotations
// in store_app/test/cart_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:store_app/src/features/cart/data/cart_repository.dart' as _i2;
import 'package:store_app/src/features/cart/domain/cart.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i2.CartRepository {
  MockCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Cart?> getCart() =>
      (super.noSuchMethod(
            Invocation.method(#getCart, []),
            returnValue: _i3.Future<_i4.Cart?>.value(),
          )
          as _i3.Future<_i4.Cart?>);

  @override
  _i3.Future<void> addToCart(int? cartId, String? productId, int? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#addToCart, [cartId, productId, quantity]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateCartItem(
    int? cartId,
    int? itemId, {
    int? quantity,
    bool? isChecked,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateCartItem,
              [cartId, itemId],
              {#quantity: quantity, #isChecked: isChecked},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeFromCart(int? cartId, int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromCart, [cartId, itemId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> checkout(int? cartId) =>
      (super.noSuchMethod(
            Invocation.method(#checkout, [cartId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
